### ISSUE TITLE
User IDs - Message Reactions

### ISSUE THREAD

**Issue by YonahFeld** [softwarebyze/Places#194] opened 2023-08-25 23:29 UTC
**Describe the bug**
When you click on the message reactions to see who gave which reaction, you see the user Id and not the first and last name

**To Reproduce**
1. go to a message with reactions
2. click on the reactions bubble (like in slack)
3. you see the user ids

**Expected behavior**
you see who gave which reaction

**Screenshots**
(https://github.com/softwarebyze/Places/assets/87882768/78519ef1-d548-4d15-9485-c903919e752c)

**Smartphone (please complete the following information):**

- Device: iPhone 12
- Version: Latest Build

**Additional context**

**Comment by Avraham-S** [comment] 2023-08-28 14:36
The issue is that the users in Stream don't have any value for the name field. I manually added a name to a user and it fixed the problem for that specific user.
![Simulator Screenshot - iPhone 14 - 2023-08-28 at 17 36 10](https://github.com/softwarebyze/Places/assets/103695563/3fb2f46a-e911-43f8-90d7-678210c2b86d)

**Comment by softwarebyze** [comment] 2023-09-05 16:53
fixed with #203

**Closed by softwarebyze** 2023-09-05 16:53 UTC
Labels: bug, sep 14
